### ISSUE TITLE
Failed to load the status-stats package

### ISSUE THREAD

**Issue by vially** [cjoh/status-stats#10]
Start atom from command line

**Atom Version**: 1.1.0
**System**: "Arch Linux"
**Thrown From**: [status-stats](https://github.com/cjoh/status-stats) package, v0.1.0
### Stack Trace

Failed to load the status-stats package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/home/vially/.atom/packages/status-stats/lib/status-stats-view.coffee:5:199)
    at /home/vially/.atom/packages/status-stats/lib/status-stats-view.coffee:10:5
    at Object.<anonymous> (/home/vially/.atom/packages/status-stats/lib/status-stats-view.coffee:71:5)
    at Object.<anonymous> (/home/vially/.atom/packages/status-stats/lib/status-stats-view.coffee:73:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.13
emmet, v2.3.13
file-icons, v1.6.11
git-log, v0.4.1
go-plus, v3.5.1
linter, v1.9.1
minimap, v4.15.0
status-stats, v0.1.0
vim-mode, v0.62.0

# Dev
No dev packages
```

**Comment by hexathos** [comment]
That's still an issue ;(

**Comment by jeffmcneill** [comment]
It is still an issue -_-

**Comment by DouglasUrner** [comment]
It's a long lived one...

**Comment by vially** [comment]
Closing due to inactivity. Also, both Atom and this package seem to be unmaintained so it's unlikely this will get fixed at this point.
